name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 3 * * FRI'

jobs:
  CI:
    continue-on-error: ${{ matrix.config.continue-on-error == 'true' }}
    strategy:
      matrix:
        config:
          - {dockerfile: 'fedora',   tag: 'fedora'}
          - {dockerfile: 'fedora',   tag: 'fedora_mpich',        build_args: 'MPI=mpich'}
          - {dockerfile: 'fedora',   tag: 'fedora_rawhide',      build_args: "TAG=rawhide\nPYTHON=python3.11", continue-on-error: 'true'}
          - {dockerfile: 'ubuntu',   tag: 'ubuntu'}
          - {dockerfile: 'ubuntu',   tag: 'ubuntu_mpich',        build_args: 'MPI=mpich'}
          - {dockerfile: 'ubuntu',   tag: 'ubuntu_rolling',      build_args: 'TAG=rolling'}
          - {dockerfile: 'ubuntu',   tag: 'ubuntu_devel',        build_args: 'TAG=devel', continue-on-error: 'true'}
          - {dockerfile: 'opensuse', tag: 'opensuse',            continue-on-error: 'true'}
          - {dockerfile: 'fedora',   tag: 'fedora_intel',        build_args: "INTEL=yes"}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker images for Docker
        uses: docker/build-push-action@v3        
        with:
          tags: espressopp/buildenv:${{ matrix.config.tag }}
          file: ${{ matrix.config.dockerfile }}
          build-args: ${{ matrix.config.build_args }}
          pull: true
          push: ${{ github.event_name == 'push' ||  github.event_name == 'schedule' }}
